<!--
MIT License

Copyright (c) 2021-2022 FoxxoSnoot

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->

@extends('layouts.admin', [
    'title' => "Ban {$user->username}"
])

@section('meta')
    <meta
        name="site-info"
        data-name="{{ config('site.name') }}"
    >
@endsection

@section('js')
    <script>
        var siteInfo = {};

        $(() => {
            const siteInfoMeta = $('meta[name="site-info"]');
            siteInfo.name = siteInfoMeta.attr('data-name');

            const presetsArray = [
                'CREATED_TO_BREAK_RULES',
                'CREATED_TO_BREAK_RULES_HISTORY',
                'COIN_FARMING',
                'INAPPROPRIATE_LINKS'
            ];

            const presets = {
                CREATED_TO_BREAK_RULES: {
                    title: 'Created to Break Rules',
                    length: 'closed',
                    category: 'none',
                    note: `Do not sign up to ${siteInfo.name} with intent on breaking our rules.`
                },

                CREATED_TO_BREAK_RULES_HISTORY: {
                    title: 'Refusal to follow TOS + Ban History',
                    length: 'closed',
                    category: 'none',
                    note: `Do not sign up to ${siteInfo.name} with intent on breaking our rules. Because of your extensive ban history and refusal to follow our Terms of Service, your account has been terminated.`
                },

                COIN_FARMING: {
                    title: 'Coin Farming',
                    category: 'coin_farming',
                    note: 'Do not use currency generated by alternative accounts for your own gain.'
                },

                INAPPROPRIATE_LINKS: {
                    title: 'Inappropriate Links',
                    category: 'inappropriate_links',
                    note: 'Do not post inappropriate links.'
                }
            };

            presetsArray.forEach((preset) => $('#presets').append(`<button class="blue small w-100 mb-2" data-auto-fill="${preset}">${presets[preset].title}</button>`));

            $('[data-auto-fill]').click(function() {
                const preset = presets[$(this).attr('data-auto-fill')];
                var messages = [];

                $('#alert').empty().hide();

                if (typeof preset['note'] !== 'undefined')
                    $('textarea[name="note"]').val(preset['note']);
                else
                    messages.push('You still need to provide a note for this preset.');

                if (typeof preset['length'] !== 'undefined')
                    $('select[name="length"]').val(preset['length']);
                else
                    messages.push('You still need to provide a length for this preset.');

                if (typeof preset['category'] !== 'undefined')
                    $('select[name="category"]').val(preset['category']);
                else
                    messages.push('You still need to provide a category for this preset.');

                if (messages.length) {
                    var output = '';

                    messages.forEach((message) => output += `<div>${message}</div>`);

                    $('#alert').html(output).show();
                }
            });
        });
    </script>
@endsection

@section('content')
    <div class="alert bg-danger text-white" id="alert" style="display:none;"></div>
    <div class="row">
        <div class="col-md-7">
            <div class="card">
                <div class="card-header">Ban User</div>
                <div class="card-body">
                    <form action="{{ route('admin.users.ban.create') }}" method="POST">
                        @csrf
                        <input type="hidden" name="id" value="{{ $user->id }}">
                        <label for="length">Length</label>
                        <select class="form-control mb-2" name="length" required>
                            @foreach ($lengths as $name => $value)
                                <option value="{{ $value }}">{{ $name }}</option>
                            @endforeach
                        </select>
                        <label for="category">Category</label>
                        <select class="form-control mb-2" name="category" required>
                            @foreach ($categories as $name => $value)
                                <option value="{{ $value }}">{{ $name }}</option>
                            @endforeach
                        </select>
                        <label for="note">Note (optional)</label>
                        <textarea class="form-control mb-3" name="note" placeholder="Note" rows="5"></textarea>
                        <button class="red" type="submit">Ban User</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">Auto Fill</div>
                <div class="card-body" id="presets"></div>
            </div>
        </div>
    </div>
@endsection
